config/routes.rb
Rails.application.routes.draw do
  get 'sales', to: 'sales#done'
  get 'sales/new'
  post 'sales', to: 'sales#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
	validates :cod, uniqueness: true
	validates :detail, presence: true
	validates :category, inclusion: { in: %w(uno dos tres cuatro cinco)}
	validates :value, numericality: { only_integer: true, greater_than: 0 }
	validates :discount, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 41}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  


  def done 
  	@sale = Sale.last
  end
  	
  
  def new
  	@sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)

    if @sale.tax.to_i == 1
      @sale.tax = 0
      @sale.total = @sale.value.to_i * (1- @sale.discount.to_f/100)
    elsif @sale.tax.to_i == 0
      @sale.tax = 19
      @sale.total = @sale.value.to_i * (1- @sale.discount.to_f/100) * 1.19
    end

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sales_path, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end

    #@sale.save
    #redirect_to sales_path

  end


  private

  def sale_params
  	params.require(:sale).permit(:cod, :detail, :category, :value, :discount, :tax, :total)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ventas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/done.html.erb
<h1>Done!</h1>
<p>El registro fue almacenado con éxito!</p>

<table class="table">

	<thead>
		<td>código</td>
		<td>detalle</td>
		<td>categoría</td>
		<td>valor</td>
		<td>descuento</td>
		<td>impuesto</td>
		<td>total</td>
	</thead>

	<tr>
		<td><%= @sale.cod %></td>
		<td><%= @sale.detail %></td>
		<td><%= @sale.category %></td>
		<td><%= @sale.value %></td>
		<td><%= @sale.discount %>%</td>
		<td><%= @sale.tax %>%</td>
		<td><%= @sale.total %></td>
	</tr>

</table>

<%= link_to 'Volver', sales_new_path %>

app/views/sales/index.html.erb
<h1>Done!</h1>
<p>El registro fue almacenado con éxito!</p>

<table class="table">

	<thead>
		<td>código</td>
		<td>detalle</td>
		<td>categoría</td>
		<td>valor</td>
		<td>descuento</td>
		<td>impuesto</td>
		<td>total</td>
	</thead>

	<tr>
		<td><%= @sale.cod %></td>
		<td><%= @sale.detail %></td>
		<td><%= @sale.category %></td>
		<td><%= @sale.value %></td>
		<td><%= @sale.discount %>%</td>
		<td><%= @sale.tax %>%</td>
		<td><%= @sale.total %></td>
	</tr>

</table>

<%= link_to 'Volver', sales_new_path %>

app/views/sales/new.html.erb
<h1>Sales New</h1>

<% if @sale.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@sale.errors.count, "error") %> impidió que esta venta se registrara:</p>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<%= form_with model: @sale, local: true do |f| %>
	
	<%= f.label :cod, "Ingrese el código" %>
	<%= f.number_field :cod %>
	<br>
	
	<%= f.label :detail, "Detalle" %>
	<%= f.text_area :detail %>
	<br>

	<%= f.label :category, "Categoría" %>
	<%= f.text_area :category %>
	<br>

	<%= f.label :value, "Valor del producto" %>
	<%= f.number_field :value %>
	<br>

	<%= f.label :discount, "Porcentaje de descuento aplicado" %>
	<%= f.number_field :discount %>
	<br>

	<%= f.label "¿Exento de IVA" %>
	<%= f.check_box :tax %>	
	<br>

	<%= f.submit "Enviar" %>
	

<% end %>